version: 2
jobs:
  one:
    docker:
      - image: debian:stretch

    steps:
      - checkout
      - run:
          name: Greeting
          command: echo "Hello, world."
      - run: sleep 25
  two:
    docker:
      - image: debian:stretch

    steps:
      - checkout
      - run:
          name: Greeting
          command: echo "Hello my fren."
      - run: sleep 25
workflow:
  version: 2
  one_and_two:
    jobs:
      - one
      - two

