version: 2
jobs:
  one:
    docker:
      - image: debian:stretch

    steps:
      - checkout
      - run:
          name: Greeting
          command: echo "Hello, world."
      - run:
          name: Print the Current Time
          command: date
      - run: sleep 25
   two:
     docker:
       - image: debian:stretch

     steps:
       - checkout
       - run:
           name: Kewl Greeting
           command: echo "Sup lil butt!"
       - run: sleep 15
workflow:
  version: 2
  one_and_two:
    jobs:
      - one
      - two

